name: build

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'static/**'
jobs:
  build-n-publish:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive 
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set up JDK 8 and 
      uses: actions/setup-java@v1
      with:
        java-version: '8.x' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    - name: Build microrts
      run: cd gym_microrts/microrts && bash build.sh && cd .. && cd ..
    - name: Build a source tarball
      run: python setup.py sdist
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
    - name: prepare gym-microrts nightly version
      run: |
        mv setup_nightly.py setup.py
        rm -rf dist
        python setup.py sdist
    - name: Publish test distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
